"use client";
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  title,
  summaryText,
  createdAt,
  fileName,
}: {
  title: string;
  summaryText: string;
  createdAt: string;
  fileName: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}\n\nGeneratedContent.\n\nGenerated on ${new Date(
      createdAt
    ).toLocaleDateString()}\n\n${summaryText}\n\nOriginal File: ${fileName}\nGenerated by Summo`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-")} - ${fileName.replace(
      /\s+/g,
      "-"
    )} - ${createdAt}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="bg-primary text-primary-foreground hover:bg-primary/90"
      onClick={handleDownload}
    >
      <Download className="w-4 h-4" />
      <span className="text-sm text-primary-foreground">Download Summary</span>
    </Button>
  );
}
